app:
    resource: "@AppBundle/Controller/"
    # resource: "@AppBundle/Resources/config/routing.yml"
    type:     annotation
    
user_registration:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }